version: "3"

services:
  backend: 
    container_name: backend
    restart: always
    build: .
    env_file: 
      - .env
    ports:
      - "5000:5000"
    expose:
      - 5000
    links:
      - redis-server
  
  redis-server:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"

